extended_valid_elements: 'i[class]'
height : 400
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons2_add:
  - link
  - unlink
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - uploadimage
  - anchor
  - link
  - unlink
plugins:
  - table
  - fullscreen
  - uploadimage
  - code
  - anchor
  - link
